### ISSUE TITLE
Missing credentials in config

### ISSUE THREAD

**Issue by rjmoggach** [kilburn/gatsby-source-s3-asset#1]
I'm using a config similar to `gatsby-source-s3-asset` 

```javascript
const AWS = require('aws-sdk')
AWS.config.update({
    accessKeyId: process.env.AWS_ACCESS_KEY,
    secretAccessKey: process.env.AWS_SECRET_KEY,
})
```

and...

```javascript
{
            resolve: 'gatsby-source-s3-asset',
            options: {
                bucketName: 's3.moggach.com',
                // domain: null, // [optional] Not necessary to define for AWS S3; defaults to `s3.amazonaws.com`
                // protocol: 'https', // [optional] Default to `https`.
                // publicDomain: null, // [optional] Use this domain to construct the public URL for the assets
            },
        },
```

I get the following error:

```shell
 ERROR #11321  PLUGIN

"gatsby-source-s3-asset" threw an error while running the sourceNodes lifecycle:

Missing credentials in config
```

Please document how to use credentials properly -
Thanks!

**Comment by kilburn** [comment]
Pass the credentials as options of the plugin:
 ```
...
{
    resolve: 'gatsby-source-s3-asset',
    options: {
        bucketName: 's3.moggach.com',
        // domain: null, // [optional] Not necessary to define for AWS S3; defaults to `s3.amazonaws.com`
        // protocol: 'https', // [optional] Default to `https`.
        // publicDomain: null, // [optional] Use this domain to construct the public URL for the assets
        accessKeyId: process.env.AWS_ACCESS_KEY,
        secretAccessKey: process.env.AWS_SECRET_KEY,
    },
},
...
```

**Comment by stcalica** [comment]
@kilburn  you need to add this to your docs, mate. 
Would help.
I know it's seen a lot in other plugins but many people name their `accessKeyId` and `secretAccessKey` params differently so could be hell for a dev trying to use this until they ook i your issues.

**Comment by stcalica** [comment]
Also, does the bucket have to publicly accessible? 
I am assuming so since it's just grabbing URLs.

**Comment by kilburn** [comment]
> @kilburn you need to add this to your docs, mate.

@stcalica you are right. I'll do it asap.

> Also, does the bucket have to publicly accessible?

Yes and no. Look at the `publicDomain` parameter. The way I'm using the plugin is with a private bucket that is also served through CloudFront. Hence the plugin fetches info from S3 (cloudfont doesn't have this functionality) but then links everything through the `publicDomain` which is a CloudFront distribution acting as CMS for the assets.

**Comment by kilburn** [comment]
How to specify credentials is now documented in the README, and I've created a separate issue #10 for the `publicDomain` explanation that I'll get to asap.
