### ISSUE TITLE
Could not find function loadNodeContent

### ISSUE THREAD

**Issue by rjmoggach** [kilburn/gatsby-source-s3-asset#2]
This is hammering my console...

```shell
"gatsby-transformer-remark" threw an error while running the onCreateNode lifecycle:

Could not find function loadNodeContent for plugin gatsby-source-s3-asset

 - nodes.js:53
    [robmoggach]/[gatsby]/dist/db/nodes.js:53:15

  - new Promise

  - nodes.js:44 module.exports.loadNodeContent
    [robmoggach]/[gatsby]/dist/db/nodes.js:44:12

  - on-node-create.js:24 Object.onCreateNode
    [robmoggach]/[gatsby-transformer-remark]/on-node-create.js:24:25

  - api-runner-node.js:234 runAPI
    [robmoggach]/[gatsby]/dist/utils/api-runner-node.js:234:37
...
```

**Comment by rjmoggach** [comment]
might be as easy as returning a null value from a function???

https://github.com/gatsbyjs/gatsby/blob/561d33e2e491d3971cb2a404eec9705a5a493602/packages/gatsby-source-filesystem/src/index.js#L3

**Comment by kilburn** [comment]
Maybe, but I'm not sure. Truth is that I'm not using gatsby-transformer-remark (and I don't have any .yml files in my bucket nor anything like that). I will have to setup some test bucket to test this out, which means it may take a while.

Can you try? You should be able to just clone this repo, make whatever changes you need, and then use your copy instead of the npm one using [yarn link](https://yarnpkg.com/lang/en/docs/cli/link/).

If you confirm that works I will release a new version so you can remove the linking thing and keep it working correctly.

**Comment by rjmoggach** [comment]
grrrr.... 

lots of deprecation warnings now for `boundActionCreators` https://gatsby.dev/boundActionCreators and `pathContext` https://gatsby.dev/pathContext

**Comment by kilburn** [comment]
I'm pretty sure this has nothing to do with this plugin. The plugin doesn't use those interfaces at all, so the warnings must be coming from somewhere else...

**Comment by kilburn** [comment]
As a side note, I think the problem with the `gatsby-transformer-remark` plugin comes from this plugin adding the (proper) `mediaType` field to the created nodes. Can you try changing [the mediaType assignment line](https://github.com/kilburn/gatsby-source-s3-asset/blob/debd4f7145136539b4e03df06fec87f7a70e7aa2/src/utils.ts#L97) to always set it as `application/octet-stream`? I think this would prevent transformer plugins from trying to do things with that info. If this works we can try to figure out how to disable this inference with a config option or something...

**Comment by rjmoggach** [comment]
this is beyond the scope of my knowledge - i'm months in to react/javascript but decades in django/python

**Comment by kilburn** [comment]
This has been fixed by just returning an empty string. For now this plugin does not strive to load the asset's contents. If we get a lot of demand for the feature I would reconsider.
